/* HOBBIES DATA — edit hobby descriptions/images here */
const HOBBY_DATA = {
  volleyball: { name:'Volleyball', img:'assets/images/hobbies/volleyball.webp', imgPos:'center center',
    desc:`<p>I picked up volleyball post-graduation, to the delight of my family, who have a long relationship with the sport. I captained a rec team of friends ranging from former athletes to total beginners. While we lost a lot early on, I shifted our focus to learning and improving together — casual, social weekly practices and simple norms like hi-fiving after every point.</p><p>Morale quickly improved and we even started winning by season's end. More importantly, it stuck — one friend who'd never felt "sporty" saw herself differently, another got fully hooked, and the team is still growing two years later.</p><p>Volleyball reinforced how I like to build communities: low pressure, high support, and people growing into it.</p>` },
  soccer:     { name:'Soccer',     img:'assets/images/hobbies/soccer.webp',    imgPos:'center center', imgRot:'180deg',
    desc:`<p>From my high school varsity team to "midnight soccer" in college to IM's at Sloan, I enjoy the strategic thinking, teamwork, and sportsmanship required to play the game. An incredibly accessible sport loved by folks across the globe, you can find pickup soccer almost anywhere.</p><p>Since participating in college IMs, I hold the belief that team sports is one of the best ways to build connection and community. Pictured is the Sloan IM team I organized, toughing out a rainy day, only to have the other team flake! Proud that we showed up for the love of the game.</p>` },
  pingpong:   { name:'Ping Pong',  img:'assets/images/hobbies/ping pong.webp', imgPos:'center 25%',
    desc:`<p>My parents met at an office ping pong tournament, so naturally, I grew up playing with my family at our basement ping pong table.</p><p>Pictured is me and a friend posing as winners of Sloan's Asian American Alliance ping pong tournament!</p>` },
  dance:      { name:'Dance',      img:'assets/images/hobbies/dance.webp',      imgPos:'center 20%',
    desc:`<p>Dance has always been a way for me to explore different modes of expression and different cultures. Growing up, I did Chinese traditional dance — we even performed at a Celtics halftime show! I learned ballet and jazz in high school, then joined a hip hop team and contemporary dance group in college. Post-college, I got into social dancing: swing, salsa, and bachata.</p><p>At Sloan I taught friends the Abracadabra (Lady Gaga) dance for a C-function event. My classmates not only put in the work — they chipped in creative direction, costumes, and skits. We created something better than any of us imagined. Dance can uniquely express the shared energy of a group.</p>` },
  running:    { name:'Running',    img:'assets/images/hobbies/run.webp',       imgPos:'center center',
    desc:`<p>My mom is a seasoned marathon runner with all the majors and more under her belt — and my biggest advocate on my own running journey (she gifts me race registrations for birthdays and holidays 😢). I have a 5k and 10k under my belt and am now training for a half marathon.</p><p>My mom also started a run club with other Asian moms, helping them go from couch to marathon. I take a page out of her book whenever I can — her dedication to the sport, community-building skills, and ability to share her passions with others.</p>` },
  music:      { name:'Music',      img:'assets/images/hobbies/Music.webp',     imgPos:'center center',
    desc:`<p>Music has always been a way for me to express myself and connect with others — from playing classical piano and chamber music growing up, to leading a free music program, to playing in Sloan's rock band.</p><p>Pictured is the <em>Tiny Living Room</em> concert I helped organize: a low-barrier, supportive environment for friends to share their musical pursuits. Check out the piano in my room to learn more.</p>` },
};

