/* ============================================================
   MODAL CONTENT — edit text/images here
============================================================ */
const CONTENT = {
  worldmap:    { title:'✦ places that shaped me',    body:`<p><strong>Chicago, South Side</strong> — where I ran a free music program for K–12 students and fell in love with building for community.</p><p><strong>Beijing / Chengdu</strong> — early-stage edtech, my first real taste of 0-to-1 building.</p><p><strong>Boston / MIT</strong> — where I'm based now, building at the intersection of tech and community.</p>` },
  piano:       { title:'♪ music',                    body:`<p>I co-president a rock band of 25 people that plays to ~900-person audiences — which is basically running a small organization.</p><p>Classically trained pianist (Chopin). Picked up bass this year. I sing and choreograph for friends.</p><p>In college I ran a free music program for K–12 students on the South Side of Chicago.</p><p><a href="javascript:void(0)">→ watch a performance</a></p>` },
  trophy:      { title:'✦ awards',                   body:`<p><strong>Mens et Manus</strong> — MIT's highest student award.</p><p><strong>GenAI Lab — Best Project</strong> — winner in class competition.</p><p><strong>Dean's List</strong> — University of Chicago.</p>` },
  shelf:       { title:'💡 entrepreneurship journey', body:`<p>I've been deliberately exploring what problems are worth building on.</p><p><strong>EdTech, China</strong> — early-stage startup, 0-to-1 in a different market.</p><p><strong>Series B media tech</strong> — operator role, scaling what's working.</p><p><strong>Fashion tech @ MIT Fuse / Martin Trust Center</strong> — explored a consumer idea.</p><p><strong>Imagination in Action</strong> — pitched to founders and investors.</p>` },
  stickynotes: { title:"◈ ideas i'm crunching",      body:`<p>🟡 How do we build technology that actually serves the communities it claims to?</p><p>🟢 What does a post-credential world look like for talent?</p><p>🔵 Why is it so hard to coordinate people around shared problems?</p><p>🟠 What would a truly community-owned platform look like?</p>` },
  mit:         { title:'MIT Sloan',                  body:`<p>Currently at MIT Sloan, at the intersection of business, technology, and community.</p><p>GenAI Lab (award-winning), Fuse entrepreneurship program, Martin Trust Center, volunteered with deltaV.</p>` },
  consulting:  { title:'📁 consulting',               body:`<p>Two years at BCG working across industries — here's what I can share.</p><p><em>Add your cases here in general terms: sector, problem, approach, outcome. Keep client details anonymous but let the thinking show through.</em></p><p>What I took away: how to structure ambiguous problems fast, how to communicate up, and how to build conviction under uncertainty.</p>` },
  laptop:      { title:'⌨ projects',                 body:`<p><strong>Relationship OS</strong> — <em>describe what it does.</em></p><p><strong>Course bidding tool</strong> — <em>describe the problem it solved.</em></p>` },
  polaroids:   { title:'⊕ community',                body:`<p>The people and communities I build with and for.</p><p><em>Add your MIT community work — events, tools built for friends.</em></p>` },
  books:       { title:'▣ reading',                  body:`<p><em>Add your top reads — one per topic area you care about.</em></p>` },
  wardrobe:    { title:'wardrobe',                   body:`<p>Ugh, I don't know what to wear.... check out <a href="#" class="modal-proj-link" data-proj="dressingroom">Dressing Room</a> in my projects!</p>` },
  door:        { title:"→ what's next",              body:`<p>I'm looking for roles where I can be close to the action — building and shipping at scale.</p><p>Chief of Staff to a founder, operator at a Series B, or building within an organization that takes ambition seriously.</p>` },
  mirror:      { title:'◎ about me',                 body:`<p>I grew up believing that building things for people you love is one of the most meaningful things you can do.</p><p>Creativity, community, structure, and navigating ambiguity. That's the throughline.</p><p><em>Write this in your own voice.</em></p>` },
  speaker:     { title:'♫ currently listening',      body:`` },
  teapot:      { title:'茶 tea time',                body:`<p>My dad is from a place with very dense tea culture — gongfu tea is a whole ritual, not just a drink.</p><p>Tea time with friends is a recurring ritual — slow, deliberate, no phones.</p>` },
  hobbies:     { title:'◍ hobbies',                  body:`<p>Movement is how I connect with people — these are my preferred ways in.</p><p><strong>Dance</strong> — Chinese classical, salsa, bachata, hip hop, contemporary. I choreograph pieces for friends when the moment calls for it.</p><p><strong>Sports</strong> — volleyball, soccer, ping pong, running. I've led two IM teams that became genuinely meaningful communities, not just leagues.</p><p>Activities first, friendship second — that's the formula.</p>` },
  contact:     { title:'✉ leave a note',             body:`<p>I'd love to hear from you. A few reasons you might be reaching out:</p><p>🔹 <strong>Startup / operator roles</strong> — CoS, growth, strategy, building something together</p><p>🔹 <strong>Interesting problems</strong> — ed tech, community infrastructure, creator tools, fashion tech</p><p>🔹 <strong>Business school</strong> — happy to chat about Sloan, the process, what I'd do differently</p><p>🔹 <strong>Just want to connect</strong> — always down for a walk, tea, or a game of volleyball</p><br><p>📬 <a href="mailto:sliu320@mit.edu">sliu320@mit.edu</a></p><p><em>(Contact form coming soon — for now email works best)</em></p>` },
};
